CREATE TABLE delivery(
    id SERIAL PRIMARY KEY,
    name CHARACTER VARYING(255) NOT NULL,
    cel NUMERIC(10, 0) NOT NULL,
    xp CHARACTER VARYING(10) NOT NULL,
    state BOOLEAN NOT NULL DEFAULT FALSE
);